global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "zbox-admin"
    static_configs:
      - targets: ["host.docker.internal:3000"]
        # if Linux docker without host.docker.internal:
        # - targets: ["172.17.0.1:3000"]

  - job_name: "wireguard"
    static_configs:
      - targets: ["172.17.0.1:9586"]
