global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zbox-admin'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'wireguard'
    static_configs:
      - targets: ['localhost:9586']
